version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.0

workflows:
  version: 2
  build_and_workflow:
    jobs:
      - build_and_deploy_jobs:
          context:
            - deploy
          filters:
            branches:
              only:
                - master

jobs:
  build_and_deploy_jobs:
    environment:
      - PROJECT_NAME=synker-app
      - GOOGLE_ZONE=us-central1-docker.pkg.dev
      - BASE_URL=https://synker-service.hummy.app
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - gcp-cli/install
      - gcp-cli/initialize

      - run:
          name: Build Image
          command: |
            docker build -t ${PROJECT_NAME} .
            docker tag ${PROJECT_NAME}:latest ${GOOGLE_ZONE}/${GOOGLE_PROJECT_ID}/hummy/${PROJECT_NAME}:${CIRCLE_SHA1:0:7}
      - run:
          name: Deploy Image
          command: |
            gcloud auth configure-docker ${GOOGLE_ZONE} --quiet
            docker push ${GOOGLE_ZONE}/${GOOGLE_PROJECT_ID}/hummy/${PROJECT_NAME}:${CIRCLE_SHA1:0:7}
      - run:
          name: Deploy New Version
          command: |
            gcloud run services update synker-app --image=${GOOGLE_ZONE}/${GOOGLE_PROJECT_ID}/hummy/${PROJECT_NAME}:${CIRCLE_SHA1:0:7} --region us-central1